# Generated by Django 2.1 on 2018-08-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='wine',
        ),
    ]
